server:
  port: 8080
spring:
  profiles: prod
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.100:31065
        namespace: e5dfe71c-4579-4e22-bc7a-ac2e5ffab032
    sentinel:
      transport:
        dashboard: 192.168.100.100:32329

logging:
  config: classpath:logback-spring.xml