server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://192.168.100.100:31324/mall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: mallcloud
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.100:31065
        namespace: e5dfe71c-4579-4e22-bc7a-ac2e5ffab032
      config:
        import-check:
          enabled: false
        enabled: false
    sentinel:
      transport:
        dashboard: 192.168.100.100:32329
  redis:
    redisson:
      config:
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          failedSlaveReconnectionInterval: 3000
          failedSlaveCheckInterval: 60000
          password: liulun666
          subscriptionsPerConnection: 5
          clientName: null
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          scanInterval: 1000
          pingConnectionInterval: 0
          keepAlive: false
          tcpNoDelay: false
          database: 0
          dnsMonitoringInterval: 5000
          address: redis://192.168.100.100:31351
        threads: 16
        nettyThreads: 32
        transportMode: "NIO"
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: 192.168.100.100
      port: 31351
      password: liulun666

seata:
  tx-service-group: default_tx_group
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      server-addr: 192.168.100.100:31065
      namespace: eb652337-fc10-4027-9e11-9484ef44f4b6
      data-id: seataServerdev.properties

swagger:
  concat:
    name: 在线文档
  base-package: com.newland.mall.system
  title: 订单服务-在线文档
  description: api文档
  enable: true

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:xml/*.xml
